name: AI MetroFlow - Local
values:
  - key: base_url
    value: 'http://127.0.0.1:8000'
  - key: supabase_url
    value: 'https://dfmdlfxcxvsbzouikwgo.supabase.co'
  - key: supabase_anon_key
    value: sb_publishable_7VvhXHDkz1yhVz_dSC43iQ_mP-B6Mpf
  - key: supabase_email
    value: shubham120104@gmail.com
  - key: supabase_password
    value: Shubham@2004
  - key: access_token
    value: ''
